# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Axel Nilsson
email: axelnilsson1994@gmail.com
description:  Welcome! My name is Axel Nilsson. I'm a student at Linnaeus University doing my last year at the Software Development and Operations program as a remote student.
              This website serves both as a blog to share intressting thoughts or solutions and as my CV. To read my full CV click the About button bellow.
              
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://axelnilsson.tech" # the base hostname & protocol for your site
twitter_username: axnion  
github_username: axnion
linkedin_username: axel-nilsson-346035a3

# Build settings
markdown: kramdown
permalink: pretty
